AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12

  Sample SAM Template for news-scraper-agent

Parameters:
  PROFILE:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: 배포에 사용할 phase

Resources:
  NewsScraperAgentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub news-scraper-agent-${PROFILE}
      ImageUri: 339712918956.dkr.ecr.ap-northeast-2.amazonaws.com/ai-news-agent/news-scraper-agent
      Timeout: 600 # 600초 (10분)
      EventInvokeConfig:
        MaximumRetryAttempts: 1
        MaximumEventAgeInSeconds: 21600 # 6시간
      MemorySize: 512
      PackageType: Image
      Architectures:
        - arm64
      Role: !GetAtt NewsScraperAgentFunctionRole.Arn
      Tags:
        PROJECT: AI_NEWS_AGENT
        PHASE: !Ref PROFILE
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: 'cron(0 10 ? * 2-6 * )'
            ScheduleExpressionTimezone: Asia/Seoul
            Name: news-scraper-agent
            Description: news-scraper-agent daily scheduler
      Environment:
        Variables:
          PROFILE: !Ref PROFILE
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
  NewsScraperAgentFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub news-scraper-agent-function-role-${PROFILE}
      Tags:
        - Key: PROJECT
          Value: AI_NEWS_AGENT
        - Key: PHASE
          Value: !Ref PROFILE
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: arn:aws:ecr:ap-northeast-2:339712918956:repository/ai-news-agent/news-scraper-agent
        - PolicyName: LambdaCloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:ap-northeast-2:339712918956:log-group:/aws/lambda/news-scraper-agent-${PROFILE}:*
        - PolicyName: EventBridgeSchedule
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:ap-northeast-2:339712918956:log-group:/aws/lambda/news-scraper-agent-${PROFILE}:*

Outputs:
  NewsScraperAgentFunction:
    Description: "News Scraper Agent Function ARN"
    Value: !GetAtt NewsScraperAgentFunction.Arn
