version = 0.1
[dev.deploy.parameters]
stack_name = "news-scraper-dev"
resolve_s3 = true
s3_prefix = "news-scraper"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
