AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-test

  Sample SAM Template for lambda-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
#Globals:
#  Function:
#    Timeout: 30

Resources:
  NewsScraperDevelop:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ai-news-noti-bot-dev
      Layers:
        - arn:aws:lambda:ap-northeast-2:764866452798:layer:chrome-aws-lambda:46
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 1024
      Timeout: 180
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENV: development
          PHASE: dev
      PackageType: Image
      ImageUri: 339712918956.dkr.ecr.ap-northeast-2.amazonaws.com/ai-news-noti-bot-develop:latest
    Metadata:
      DockerTag: latest
      DockerContext: ../../
      Dockerfile: Dockerfile
#      BuildMethod: esbuild
#      BuildProperties:
#        Minify: true
#        Target: "es2020"
#        Sourcemap: true
#        EntryPoints:
#          - index.ts
#        External:
#          - '@sparticuz/chromium'
#          - puppeteer-core

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
